# Generated by Django 3.1.7 on 2021-03-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_all_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_posts',
            name='image',
            field=models.ImageField(upload_to='media/all_posts'),
        ),
    ]
