# Generated by Django 3.1.7 on 2021-03-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210307_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_posts',
            name='image',
            field=models.ImageField(upload_to='all_posts/'),
        ),
    ]
