# Generated by Django 3.1.7 on 2021-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210311_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_posts',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
