# Generated by Django 3.1.7 on 2021-04-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_all_posts_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_posts',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
